In [2]:
import numpy as np

In [3]:
liste = np.arange(10, 100, 10) ##Creation du tableau a une ligne avec arange

In [4]:
liste

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
matrices= liste.reshape(3,3) #Creation de la matrice 3,3

In [6]:
matrices 

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
dimension = matrices.shape  ##Dimension de la matrice

In [8]:
dimension

(3, 3)

In [9]:
matrices[:,1]  ##Affichage de la deuxieme colonne

array([20, 50, 80])

In [10]:
matrices[1,:]  ##affichage de la deuxieme ligne 

array([40, 50, 60])

## Calcul de la moyenne de chaque colone

In [11]:
moy = np.mean(matrices, axis=0)

In [12]:
moy

array([40., 50., 60.])

## 5 - Calcul de la somme de chaque ligne

In [13]:
sommeLigne = np.sum(matrices , axis = 1)

In [14]:
sommeLigne

array([ 60, 150, 240])

## 6 - Transformation de la matrice en tableau  D1

In [15]:
D1 =  matrices.flatten() ##flatten creer une copie de la memoire=>Occupe la memeoire, lent

In [16]:
D1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
D1= matrices.reshape(9,) ##deuxieme methode quand on connait la taille des element du tableau

In [18]:
D1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
matrices.reshape(-1)  ##Dans cette method plus besoin de preciser la taille numpy calcul lui meme,
## cette methode est moins lent et occupe pas  trop la memeoire 

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
matrices.ravel() ##Renvoi en general une vue(plus rapide, moins de memoire)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## 7- Recherche du maximum dans un tableu

In [22]:
matrices

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
Tab = matrices.ravel()

In [24]:
Tab

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
maximum = np.max(Tab)

In [31]:
maximum  ##Un nombre entier maximum de type int 

np.int64(90)

int(maximum) 

## 8-Recherche du mimimum 

In [33]:
minimum = np.min(Tab)

In [34]:
minimum  ##minimum de type int numpy

np.int64(10)

In [35]:
int(minimum)

10

## 9- La médiane  : ***np.median()***

### C'est la valeur situes au milieu d'un ensemble de donnes lorsquels sont classes dans l'ordre
### **Role** : Elle permet de connaitre la valeur centrale d'un jeu de donnes .Elle est peut influnce par des valeur extremes

In [36]:
matrices  ##Avec une matrice 3D

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [37]:
np.median(matrices, axis=1) ## ==>MedLigne1=20 , medLigne2=50 medLigne3=80

array([20., 50., 80.])

In [38]:
Tab ##Avec un tableau 

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.median(Tab)  ##Le centre est 50.0 (Un type float numpy)

np.float64(50.0)

In [42]:
float(np.median(Tab))

50.0

## 10- Ecart-type :***np.std()*** , Signifie **Standard Deviation**

### L'ecart-type mesure a quel point les donnes sont dispersees autour de la moyennes 

In [43]:
Tab ##Tabeleau D1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
moyenne  = np.mean(Tab)

In [45]:
moyenne

np.float64(50.0)

In [48]:
float(moyenne) ##Moyenne du tableau c'est la meme que la medianne trouve precedemment

50.0

In [50]:
Ecart_type = np.std(Tab)

In [51]:
Ecart_type

np.float64(25.81988897471611)

In [52]:
float(Ecart_type)  ##Ecart- type du tabeleau Tab

25.81988897471611

## 11- Variance : ***np.var()***

### La variance mesure egalement la dispersionr des donnes :**C'est le carre de l'Ecart-type** 
### Utilite : Elle sert a mesure la variabilites des donnes

In [53]:
Tab

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
float(Ecart_type)  ##Ecart-type de Tab

25.81988897471611

In [55]:
Variance = np.var(Tab)

In [56]:
Variance

np.float64(666.6666666666666)

In [57]:
float(Variance) ##Variance

666.6666666666666

In [58]:
float(Ecart_type)**2  ## ==> variance = (Ecart_type)**2

666.6666666666666

## PARTIE 2 : OPERATION SUR LES TABLEAUX NUMPY

In [60]:
A=np.arange(3,6,2)

In [61]:
A ##tableau 1

array([3, 5])

#### Soit A et  B deux tableaux de meme dimension

In [67]:
B= np.arange(1,5,2)

In [68]:
B

array([1, 3])

### 1-Addition de tableaux (+)

In [71]:
A+B  ##Sommecolonne= colone +colone et somme Ligne aussi
##On peut aussi utiliser np.add(A,B)

array([4, 8])

### 2-Soustraction (-)

In [72]:
A-B  ##On peut aussi utiliser la fonction np.substract(A,B)

array([2, 2])

### 3-Multiplication par scalaire (*)

In [75]:
A*3

array([ 9, 15])

### 4- Division(/)

In [77]:
A/2  ##Om peut aussi utiliser : np.divide()

array([1.5, 2.5])

### 5 - Multiplication element par element(Produit de deux tabelaux)

In [79]:
A*B

array([ 3, 15])

### 6- Puissance (**)

In [81]:
A**2 ##Eleve chaque element du tableau a la puissance 2  on peut aussi utiliser
##                          la fonction : np.power(A)

array([ 9, 25])

### 7- Modulo (%)

In [83]:
A%2

array([1, 1])

## PARTIE 3 : LES OPERATIONS MATRICIELLES

### A - Creation de deux matrice A et B

In [118]:
Tab1=np.arange(1, 90, 10)

In [119]:
Tab1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81])

In [132]:
Tab2 = np.arange(1,10,1)

In [133]:
Tab2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
A= Tab1.reshape(3,3)

In [135]:
A  ## MATRICE A CREER 

array([[ 1, 11, 21],
       [31, 41, 51],
       [61, 71, 81]])

In [136]:
B= Tab2.reshape(3,3)

In [137]:
B  ## MATRICE B CRREER 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 1- Le produit matriciel (@)

In [138]:
A@B  ## @ C'est l'arobase.Son nom en anglais : dot 

array([[ 192,  225,  258],
       [ 552,  675,  798],
       [ 912, 1125, 1338]])

In [139]:
np.dot(A, B)  ##MEME METHODE 

array([[ 192,  225,  258],
       [ 552,  675,  798],
       [ 912, 1125, 1338]])

### 2- Le determinant

In [142]:
determinant = np.linalg.det(A)

In [143]:
determinant 

np.float64(2.446130729665928e-13)

In [145]:
float(determinant)

2.446130729665928e-13

In [146]:
#### Le determinant permet de savoir si une matrice est inversible 

### 3 - L'inverse d'une matrice

In [148]:
I = np.linalg.inv(A) ## Inverse de la matrice A

In [149]:
I

array([[-1.22642668e+15,  2.45285337e+15, -1.22642668e+15],
       [ 2.45285337e+15, -4.90570674e+15,  2.45285337e+15],
       [-1.22642668e+15,  2.45285337e+15, -1.22642668e+15]])

### 4- La matrice identité

#### La fonction "***np.eye(n)***" permet de creer les matrice identite avec n une valeur a specifier

In [156]:
Indetite5 = np.eye(5)

In [157]:
Indetite1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5-  LA FONCTION " diag() "
#### Cette fonction nou permet de recuperer les diagonales d'une matrice
#### on ecrit sous cette forme np.diag(matrice, k) avec :
#### - k>0 on prend les diagonales qui sont au dessus
#### - Pour k<0 on prend les diagonales qui sont en dessous de la diagonale principale
#### -Pour k=0 on retrouve la diagonale principale

In [163]:
np.diag(A, k= 0)

array([ 1, 41, 81])

In [164]:
np.diag(A, k=-1)

array([31, 71])

### 6- La transposée (T)

In [165]:
Transpose_A = A.T ##La transpose de la matrice A

In [166]:
Transpose_A 

array([[ 1, 31, 61],
       [11, 41, 71],
       [21, 51, 81]])

In [167]:
np.size(A)  ##Donne la taille de la madtrice ou du tableau

9

In [ ]:
### <h1 align ="center" style = "color : red" > 1- Le broadcasting</h1>

## 7- Trace  '***np.trace()***'

In [168]:
Trace_A = np.trace(A)

In [169]:
Trace_A 

np.int64(123)

In [170]:
int (Trace_A)

123

## 8- Valeur propres et vecteurs propres '***np.linalg.eig()***'

In [177]:
val_propresVecteur_propres = np.linalg.eig(A)

In [178]:
val_propresVecteur_propres

EigResult(eigenvalues=array([ 1.36214456e+02, -1.32144564e+01, -7.58787732e-15]), eigenvectors=array([[ 0.17239504,  0.79812735,  0.40824829],
       [ 0.50812449,  0.10218355, -0.81649658],
       [ 0.84385393, -0.59376026,  0.40824829]]))

In [179]:
hugo = [20,34,59]
jean = [133,443,24]
emilie = [33,355,53]
rachele = [333,555,1131]

Table = [hugo, jean, emilie, rachele]

In [181]:
Table

[[20, 34, 59], [133, 443, 24], [33, 355, 53], [333, 555, 1131]]