## -------------------------------------------------------
##   L'APPRENTISSAGE AVEC LE PACkAGE NUMPY
## ---------------------------------------------------------

In [1]:
liste=[1033,32,42,42]

In [2]:
liste

[1033, 32, 42, 42]

### CONVERSION D'UNE LISTE EN TABLEAU DE TYPE DE NUMPY POUR 
#### Pour ce faire on utilise la fonction **array**

In [8]:
import numpy as np

In [16]:
L2=[[1,2],[33,32],[65,9]]

In [17]:
L2

[[1, 2], [33, 32], [65, 9]]

In [18]:
MATRICE2=np.array(L2)

In [19]:
MATRICE2

array([[ 1,  2],
       [33, 32],
       [65,  9]])

### TABLEAU A TROIS DIMENSSION

#### Utilisation des fonction range() et **arange()**, le plus important est la fonction arange car cette fonction nous permetra de creer des tableau a 3 ou plus

In [20]:
np.arange(10)  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(100)    ##utilisation de la fonction arange()==Une seule dimension

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
np.arange(5, 20, 7)  ##RANGE AVEC arange(Debut, fin , pas)

array([ 5, 12, 19])

In [23]:
np.arange(30,3,-2)

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4])

In [24]:
np.arange(5.0)  ##Les nombres passer en parametre constutuerons le tableau d'element a otenir

array([0., 1., 2., 3., 4.])

In [25]:
#la fonction arange() permet de creer des tableau numpy de facon automatique

##  A=====                       LA METHODE **reshape()**

In [26]:
##cette methode nous permet de creer un nouvel tableau a partir d'un autree  tableau avec des dimenssion a specifier

In [27]:
a=np.arange(1, 13,1) ##Ce tableau est a une seul dimension(Les 
                    #fonction arange nous permet de creer des tableau automatique a une seule dimension

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
a.shape  ##Affiche la tailles des elements

(12,)

In [30]:
b=a.reshape((3,4))  ## 3x4=Nombre d'elment du tableau a 

In [31]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
b.shape  ##Dimenssion du tableau 

(3, 4)

In [33]:
 ##Les dimmension doit etre compatible avec le nombre d'element du tableau :soit b=a.reshape(x,y) , donc  taille=x*y

## B-- la méthode **resize** et la fonction **resize**
#### --------------------------------------------------------

In [34]:
tab=np.arange(15)

In [35]:
tab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
tab.resize(3,5)  ##Aplication de la fonctiokn resize() est presque pareil a la methode reshape(), lorque les le produit des dimension est egale au total de element du tableau 

In [37]:
tab  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
table=np.arange(12)

In [42]:
table

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
table.resize((3,4))

In [46]:
table 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
table.resize((5,6)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [52]:
table.resize((5,6), refcheck=False)  #la methode resize(), permet de creer un nouvel tableeau avec
# les dimenssion choisie, pour eviter l'erreur on met refcheck sur Faux, si le propduit des
# dimension du tableau est superieur au nombre d'element du tableau python complelte le reste par des zeros.

In [53]:
table

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [54]:
table.resize((2,3), refcheck=False) ##Test avec dim(2,3)<nombre d'element du tableau 

In [55]:
table  ##Pour cela python abandonne le reste et recreer un nouveau tableau en respectant les nouvellles dimenssion

array([[0, 1, 2],
       [3, 4, 5]])

#### Utilisation de la fonction de la fonction ***resize()***

In [63]:
tab1=np.arange(9)

In [64]:
tab1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
m=np.resize(tab1, (5,6))

In [66]:
m ## On remarque la fonction resize elle duplique le  le nombre d'element du tableau initial jusqu'a atteindre les dimenssion indique 

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2],
       [3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2]])

  ## PARTIE 2 -- CONSTRUCTION AUTOMATIQUE DE TABLEAU

In [67]:
np.zeros(4) ## Creation d'un tableau null

array([0., 0., 0., 0.])

In [71]:
np.zeros((4,3)) ##Creation d'une matirce null

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.ones(4) ##Creation d'un tableau contenant des 1

array([1., 1., 1., 1.])

In [74]:
np.ones((5,4)) #Creation d'une matrice contenant que 1 comme des element de la matice

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
###On remarque que  tout les element des tableau et matrice sont tous de type 
##float par defaut donc si on veut un tableau ontenenant es int il suiffit de specifier comme suit ((np.zeros((a,b), type)

In [76]:
np.ones((5,4), int )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [77]:
np.zeros((4,3), int )

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
# ##Dans les cas precedent on a remarque quil existe une methode numpy comme np.zeros et np.ones qui donne des zero et des 1 .
# Maintenant il existe une autre metode qui permet de specifier , le nombre qu'on veut avoir 

In [82]:
np.full((5,5), 7) #on peut aussi specifier le type pour cette fonction elle est faite a defeaut avec le type int 
#                                          np.ful((a,b), c, type)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

 ### CREATION DE LA MATRICES IDENTITE pour ce faire on utilise la fonction  " ***eye()*** "

In [104]:
np.eye(4)  ## on peut aussi preciser les dimension par exemple np.eye(4,3) || ligne :4 et 3 colonne

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### A- LA FONCTION  " ***diag()*** "
#### Cette fonction nou permet de recuperer les diagonales d'une matrice 
#### on ecrit sous cette forme ***np.diag(matrice, k)***  avec :                            
#### - k>0 on prend les diagonales qui sont au dessus 
#### - Pour k<0 on prend les diagonales qui sont en dessous de la diagonale principale 
#### -Pour k=0 on retrouve la diagonale principale

In [87]:
matrice = np.arange(1,17).reshape(4,4)

In [88]:
matrice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
np.diag(matrice, k=0)

array([ 1,  6, 11, 16])

In [94]:
np.diag(matrice,k= -1)

array([ 5, 10, 15])

In [95]:
np.diag(matrice,k= 3)

array([4])

#### 1- Creation d'une matrice diagonale a partire d'un tableau a une dimension

In [96]:
tab3=np.array([12,4,5,7,9])  ##CREATION DU TABLEAU A UNE SEUL DIMENSION

In [97]:
tab3

array([12,  4,  5,  7,  9])

In [98]:
Matrice_Diagonale=np.diag(tab3)

In [99]:
Matrice_Diagonale

array([[12,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  5,  0,  0],
       [ 0,  0,  0,  7,  0],
       [ 0,  0,  0,  0,  9]])

In [101]:
Matrice_Diagonale1=np.diag(tab3, k=-2)  ## nouvelle diagonale en dessous de la diagonale principale a un pas de 2

In [102]:
Matrice_Diagonale1    

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [12,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0]])

### Fonction     " ***linspace()*** "

In [106]:
np.linspace(0,7,100)  #np.linspace(debut, fin,nbreElement)

array([0.        , 0.07070707, 0.14141414, 0.21212121, 0.28282828,
       0.35353535, 0.42424242, 0.49494949, 0.56565657, 0.63636364,
       0.70707071, 0.77777778, 0.84848485, 0.91919192, 0.98989899,
       1.06060606, 1.13131313, 1.2020202 , 1.27272727, 1.34343434,
       1.41414141, 1.48484848, 1.55555556, 1.62626263, 1.6969697 ,
       1.76767677, 1.83838384, 1.90909091, 1.97979798, 2.05050505,
       2.12121212, 2.19191919, 2.26262626, 2.33333333, 2.4040404 ,
       2.47474747, 2.54545455, 2.61616162, 2.68686869, 2.75757576,
       2.82828283, 2.8989899 , 2.96969697, 3.04040404, 3.11111111,
       3.18181818, 3.25252525, 3.32323232, 3.39393939, 3.46464646,
       3.53535354, 3.60606061, 3.67676768, 3.74747475, 3.81818182,
       3.88888889, 3.95959596, 4.03030303, 4.1010101 , 4.17171717,
       4.24242424, 4.31313131, 4.38383838, 4.45454545, 4.52525253,
       4.5959596 , 4.66666667, 4.73737374, 4.80808081, 4.87878788,
       4.94949495, 5.02020202, 5.09090909, 5.16161616, 5.23232

###  CREATION DE TABLEAUX ALEATOIRES

In [107]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [108]:
np.random.rand(10)   

array([0.87504682, 0.06759404, 0.01138719, 0.79099457, 0.08208418,
       0.09944391, 0.13493063, 0.65395167, 0.3067121 , 0.42475433])

In [111]:
np.random.rand(4,5) ## Cela permet de creer des element du tableau compris [0, 1]

array([[0.91192662, 0.37118732, 0.4986618 , 0.33679648, 0.67847278],
       [0.35878169, 0.78239531, 0.09726435, 0.49904851, 0.17842055],
       [0.62792544, 0.26703197, 0.77819933, 0.46208894, 0.52720403],
       [0.99344869, 0.19845516, 0.50034037, 0.00342382, 0.83568065]])

 ###  B- Fonction "***random.randn()*** "
#### Cette fonction nous permet d'obtenir un tableau ou une matrice dont les element sont defini entre [-1, 1]

In [114]:
np.random.randn(10) ##Tableau de 10 element defini sur [-1, 1]

array([-1.50508584, -1.20278943,  0.21108611, -0.53495008,  0.00348119,
       -0.29089354, -0.63512134, -1.27945764,  0.00882909,  0.21275963])

In [115]:
np.random.randn(5,7)

array([[-0.03045591,  1.39550192,  0.69210887, -0.67683168, -0.40642055,
        -0.57471643, -0.87892797],
       [ 0.31753548, -0.65756871, -0.13287556,  1.2279873 ,  0.20678506,
         0.07747983, -1.58108927],
       [ 1.91332944, -0.91993144,  1.91991941,  0.01147216,  2.3399218 ,
         1.36936383,  0.5375889 ],
       [ 1.42158721, -1.21175308,  0.91491851, -1.47590884,  1.06934742,
        -1.15267103,  0.00769011],
       [ 0.27743033,  0.92105606, -0.01795629, -1.0957081 , -3.02547837,
         0.87544588,  0.35193482]])

### C-  Fonction " ***random.randint()*** "
#### Cette fonction permet de trouver un nombre entier de facon aleatoire contenue dans un intervalle

In [118]:
np.random.randint(0,100)  

66

In [125]:
np.random.randint(1,100,20)

array([84,  4, 51, 69, 92, 92, 85, 84, 57, 45, 68, 35, 97, 16,  2, 47, 21,
       84, 16, 31], dtype=int32)

In [126]:
matrice = np.random.randint(0, 100, (4,3))  ##Creation  de la matrice avec des nombre aleatoires tout en precisant les dicmension

In [127]:
matrice

array([[23, 86, 92],
       [ 6, 52, 56],
       [68, 83, 16],
       [29,  6, 84]], dtype=int32)